In [1]:
WORK_DIR_PATH = ".."

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
os.chdir(WORK_DIR_PATH)
print(f"DIRECTORY: {os.getcwd()}")

DIRECTORY: c:\Users\jayar\Desktop\바탕 화면\REPO\PAPER REVIEW\RECSYS\02_MLP\14_RS-NAIS

In [4]:
import sys
sys.path.append("src")

# Config

In [5]:
import json
import pandas as pd
from pointwise import utils

# Amazon Beauty

In [6]:
# JSON lines 형식의 파일 열기
PATH = './data/origin/abeauty.json'
MODE = 'r'
ENCODING = 'utf-8'

kwargs = dict(
    file=PATH, 
    mode=MODE, 
    encoding=ENCODING,
)

with open(**kwargs) as f:
    records = [
        json.loads(line) 
        for line in f
    ]

# reviewerID와 asin만 추출
filtered_records = [
    {
        'reviewerID': r['reviewerID'], 
        'asin': r['asin'],
    } 
    for r in records
]

# DataFrame으로 변환
df = pd.DataFrame(filtered_records)

In [7]:
df

           reviewerID        asin
0      A2HOI48JK8838M  B00004U9V2
1      A1YIPEY7HX73S7  B00004U9V2
2      A2QCGHIJ2TCLVP  B00004U9V2
3      A2R4UNHFJBA6PY  B00004U9V2
4      A2QCGHIJ2TCLVP  B00004U9V2
...               ...         ...
34273  A2CF66KIQ3RKX3  B01GOZ61O8
34274  A1LKOIZXPQ9VG0  B01GOZ61O8
34275   AV2RWORXTFRJU  B01H353HUY
34276  A22S7D0LP8GRDH  B01H353HUY
34277   AAF5D1LTFGB7L  B01HGSJPMW

[34278 rows x 2 columns]

In [8]:
# Columns
kwargs = dict(
    df=df,
    user_col='reviewerID', 
    item_col='asin', 
)

data = utils.standardizer.main(**kwargs)

In [9]:
data

       userId  itemId
0        1487       2
1         948       2
2        1763       2
3        1786       2
4        1763       2
...       ...     ...
34273    1345    1578
34274     601    1578
34275    3694    1581
34276    1069    1581
34277    3083    1582

[34278 rows x 2 columns]

In [10]:
# data Description
kwargs = dict(
    df=data,
    percentile=0.9,
)

utils.desc.main(**kwargs)

number of user: 3819
number of item: 1581
total interaction: 34278
interaction density: 0.5677 %
max interaction of user: 127
max interaction of item: 1221
top 10.0 % interaction of user: 15.0
top 10.0 % interaction of item: 30.0
mean interaction of user: 8
mean interaction of item: 21

In [11]:
PATH = "./data/abeauty.csv"

kwargs = dict(
    path_or_buf=PATH,
    index=False, 
    header=True,
)

data.to_csv(**kwargs)

# Amazon Music

In [12]:
# JSON lines 형식의 파일 열기
PATH = './data/origin/amusic.json'
MODE = 'r'
ENCODING = 'utf-8'

kwargs = dict(
    file=PATH, 
    mode=MODE, 
    encoding=ENCODING,
)

with open(**kwargs) as f:
    records = [
        json.loads(line) 
        for line in f
    ]

# reviewerID와 asin만 추출
filtered_records = [
    {
        'reviewerID': r['reviewerID'], 
        'asin': r['asin'],
    } 
    for r in records
]

# DataFrame으로 변환
df = pd.DataFrame(filtered_records)

In [13]:
df

           reviewerID        asin
0      A3EBHHCZO6V2A4  5555991584
1       AZPWAXJG9OJXV  5555991584
2      A38IRL0X2T4DPF  5555991584
3      A22IK3I6U76GX0  5555991584
4      A1AISPOIIHTHXX  5555991584
...               ...         ...
64701  A1PQ1PESSO8CMO  B00KILDVEI
64702  A120RH58WVY4W6  B00KILDVEI
64703  A19VJ2IQLO50G0  B00KILDVEI
64704   AUDSM2CTLLW1Q  B00KILDVEI
64705  A1GN8UJIZLCA59  B00KILDVEI

[64706 rows x 2 columns]

In [14]:
# Columns
kwargs = dict(
    df=df,
    user_col='reviewerID', 
    item_col='asin', 
)

data = utils.standardizer.main(**kwargs)

In [15]:
data

       userId  itemId
0        3541       2
1        5531       2
2        3307       2
3        1580       2
4         429       2
...       ...     ...
64701    1079    3569
64702      86    3569
64703     401    3569
64704    5323    3569
64705     675    3569

[64706 rows x 2 columns]

In [16]:
# data Description
kwargs = dict(
    df=data,
    percentile=0.9,
)

utils.desc.main(**kwargs)

number of user: 5541
number of item: 3568
total interaction: 64706
interaction density: 0.3273 %
max interaction of user: 578
max interaction of item: 272
top 10.0 % interaction of user: 20.0
top 10.0 % interaction of item: 40.0
mean interaction of user: 11
mean interaction of item: 18

In [17]:
PATH = "./data/amusic.csv"

kwargs = dict(
    path_or_buf=PATH,
    index=False, 
    header=True,
)

data.to_csv(**kwargs)

# Last.FM

In [18]:
# Upload Data
PATH = "./data/origin/lastfm.dat"
df = pd.read_csv(filepath_or_buffer=PATH, sep='\t')

In [19]:
df

       userID  artistID  weight
0           2        51   13883
1           2        52   11690
2           2        53   11351
3           2        54   10300
4           2        55    8983
...       ...       ...     ...
92829    2100     18726     337
92830    2100     18727     297
92831    2100     18728     281
92832    2100     18729     280
92833    2100     18730     263

[92834 rows x 3 columns]

In [20]:
# Columns
kwargs = dict(
    df=df,
    user_col='userID', 
    item_col='artistID', 
)

data = utils.standardizer.main(**kwargs)

In [21]:
data

       userId  itemId
0           2      47
1           2      48
2           2      49
3           2      50
4           2      51
...       ...     ...
92829    1893   17617
92830    1893   17618
92831    1893   17619
92832    1893   17620
92833    1893   17621

[92834 rows x 2 columns]

In [22]:
# data Description
kwargs = dict(
    df=data,
    percentile=0.9,
)

utils.desc.main(**kwargs)

number of user: 1892
number of item: 17632
total interaction: 92834
interaction density: 0.2783 %
max interaction of user: 50
max interaction of item: 611
top 10.0 % interaction of user: 50.0
top 10.0 % interaction of item: 8.0
mean interaction of user: 49
mean interaction of item: 5

In [23]:
PATH = "./data/lastfm.csv"

kwargs = dict(
    path_or_buf=PATH,
    index=False, 
    header=True,
)

data.to_csv(**kwargs)

# Movie Lens

In [24]:
# Upload Data
PATH = "./data/origin/movielens.csv"
df = pd.read_csv(PATH)

In [25]:
df

        userId  movieId  rating   timestamp
0            1        0     4.0   964982703
1            1        2     4.0   964981247
2            1        5     4.0   964982224
3            1       43     5.0   964983815
4            1       46     5.0   964982931
...        ...      ...     ...         ...
100831     610     9416     4.0  1493848402
100832     610     9443     5.0  1493850091
100833     610     9444     5.0  1494273047
100834     610     9445     5.0  1493846352
100835     610     9485     3.0  1493846415

[100836 rows x 4 columns]

In [26]:
# Columns
kwargs = dict(
    df=df,
    user_col='userId', 
    item_col='movieId', 
)

data = utils.standardizer.main(**kwargs)

In [27]:
data

        userId  itemId
0            2       2
1            2       4
2            2       7
3            2      45
4            2      48
...        ...     ...
100831     611    9418
100832     611    9445
100833     611    9446
100834     611    9447
100835     611    9487

[100836 rows x 2 columns]

In [28]:
# data Description
kwargs = dict(
    df=data,
    percentile=0.9,
)

utils.desc.main(**kwargs)

number of user: 610
number of item: 9724
total interaction: 100836
interaction density: 1.7000 %
max interaction of user: 2698
max interaction of item: 329
top 10.0 % interaction of user: 400.3
top 10.0 % interaction of item: 27.0
mean interaction of user: 165
mean interaction of item: 10

In [29]:
PATH = "./data/movielens.csv"

kwargs = dict(
    path_or_buf=PATH,
    index=False, 
    header=True,
)

data.to_csv(**kwargs)